// Code generated by (di v2); DO NOT EDIT.
// Graph: specs/graph.json
// Graph-SHA256: 5826399a6614c2bbbc8d63b9f15d5588af5a88491d61bfeac3dc2b1dda5afc38

package v4

import (
	"fmt"
	di "github.com/sghaida/odi/di"
	config "github.com/sghaida/odi/examples/v4/config"
)

type BuildAppV4Result struct {
	Alpha *Alpha
	Beta  *Beta
	Core  *Core
}

func BuildAppV4(cfg config.Config, reg di.Registry) (BuildAppV4Result, error) {
	var res BuildAppV4Result
	alphaB := NewAlphaV4(cfg)
	betaB := NewBetaV4(cfg)
	coreB := NewCoreV4(cfg)
	alphaB.InjectBeta(betaB.UnsafeImpl())
	betaB.InjectAlpha(alphaB.UnsafeImpl())
	coreB.InjectAlpha(alphaB.UnsafeImpl())
	coreB.InjectBeta(betaB.UnsafeImpl())
	alphaSvc, err := alphaB.BuildWith(reg)
	if err != nil {
		return res, fmt.Errorf("BuildAppV4: build alpha failed: %w", err)
	}
	res.Alpha = alphaSvc
	betaSvc, err := betaB.BuildWith(reg)
	if err != nil {
		return res, fmt.Errorf("BuildAppV4: build beta failed: %w", err)
	}
	res.Beta = betaSvc
	coreSvc, err := coreB.BuildWith(reg)
	if err != nil {
		return res, fmt.Errorf("BuildAppV4: build core failed: %w", err)
	}
	res.Core = coreSvc

	return res, nil
}
