version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - staticcheck   # includes gosimple + unused
    - errcheck
    - revive
    - ineffassign
    - bodyclose

  settings:
    revive:
      rules:
        - name: var-naming
        - name: receiver-naming
        - name: error-return
        - name: error-strings

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
