// Code generated by di1; DO NOT EDIT.

package v3

import (

	"fmt"

	"github.com/sghaida/odi/examples/v3/config"

)

// DecisionSvcV3 is a public facade/builder.
type DecisionSvcV3 struct {
	svc *DecisionSvc
	hasDecisionStore bool
	hasFraudChecker bool
}
func NewDecisionSvcV3(cfg config.Config) *DecisionSvcV3 {
	return &DecisionSvcV3{
		svc: NewDecisionSvc(cfg),
	}
}

func (b *DecisionSvcV3) InjectDecisionStore(dep DecisionStore) *DecisionSvcV3 {
	b.svc.store = dep
	b.hasDecisionStore = true
	return b
}

func (b *DecisionSvcV3) InjectFraudChecker(dep FraudChecker) *DecisionSvcV3 {
	b.svc.checker = dep
	b.hasFraudChecker = true
	return b
}

func (b *DecisionSvcV3) Inject(fn func(*DecisionSvc)) *DecisionSvcV3 {
	if fn != nil {
		fn(b.svc)
	}
	return b
}

func (b *DecisionSvcV3) Build() (*DecisionSvc, error) {
	if !b.hasDecisionStore {
		return nil, fmt.Errorf("DecisionSvcV3 not wired: missing required dep DecisionStore")
	}
	if !b.hasFraudChecker {
		return nil, fmt.Errorf("DecisionSvcV3 not wired: missing required dep FraudChecker")
	}
	return b.svc, nil
}

func (b *DecisionSvcV3) MustBuild() *DecisionSvc {
	svc, err := b.Build()
	if err != nil {
		panic(err)
	}
	return svc
}
