// Code generated by di1; DO NOT EDIT.

package v3

import (

	"fmt"

	"github.com/sghaida/odi/examples/v3/config"

)

// FraudSvcV3 is a public facade/builder.
type FraudSvcV3 struct {
	svc *FraudSvc
	hasTransactionGetter bool
	hasDecisionWriter bool
}
func NewFraudSvcV3(cfg config.Config) *FraudSvcV3 {
	return &FraudSvcV3{
		svc: NewFraudSvc(cfg),
	}
}

func (b *FraudSvcV3) InjectTransactionGetter(dep TransactionGetter) *FraudSvcV3 {
	b.svc.txGetter = dep
	b.hasTransactionGetter = true
	return b
}

func (b *FraudSvcV3) InjectDecisionWriter(dep DecisionWriter) *FraudSvcV3 {
	b.svc.writer = dep
	b.hasDecisionWriter = true
	return b
}

func (b *FraudSvcV3) Inject(fn func(*FraudSvc)) *FraudSvcV3 {
	if fn != nil {
		fn(b.svc)
	}
	return b
}

func (b *FraudSvcV3) Build() (*FraudSvc, error) {
	if !b.hasTransactionGetter {
		return nil, fmt.Errorf("FraudSvcV3 not wired: missing required dep TransactionGetter")
	}
	if !b.hasDecisionWriter {
		return nil, fmt.Errorf("FraudSvcV3 not wired: missing required dep DecisionWriter")
	}
	return b.svc, nil
}

func (b *FraudSvcV3) MustBuild() *FraudSvc {
	svc, err := b.Build()
	if err != nil {
		panic(err)
	}
	return svc
}
